backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page' }
          - {
              label: 'Author Data',
              name: authorData,
              widget: object,
              collapsed: false,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Background, name: background, widget: image },
                  { label: 'Introduction', name: introduction, widget: string },
                  { label: 'About Me', name: about, widget: text },
                  {
                    label: 'Typing Text',
                    name: typingText,
                    widget: list,
                    fields:
                      [{ label: 'I am text', name: iAm, widget: string }, { label: 'Delay (ms)', name: delay, widget: number, value_type: 'int' }],
                  },
                ],
            }
          - {
              label: Skills,
              name: skills,
              widget: object,
              collapsed: false,
              fields:
                [
                  { label: 'Title', name: 'title', widget: string },
                  { label: 'Subtitle', name: subtitle, widget: string },
                  { label: 'More Details', name: extra, widget: markdown, default: null, required: false },
                  {
                    label: 'Skills',
                    name: list,
                    widget: list,
                    fields:
                      [
                        { label: 'Class Name', name: classNames, widget: string },
                        { label: 'Skill Name', name: skillName, widget: string },
                        { label: Image, name: 'image', widget: image, required: false, default: null },
                        { label: 'Type', name: 'type', widget: 'select', options: ['tools', 'language', 'framework'] },
                      ],
                  },
                ],
            }
          - {
              label: Projects,
              name: projects,
              widget: object,
              collapsed: false,
              fields:
                [
                  { label: 'Title', name: 'title', widget: string },
                  { label: 'Subtitle', name: subtitle, widget: string },
                  {
                    label: 'Projects List',
                    name: list,
                    widget: list,
                    fields:
                      [
                        { label: 'Title', name: 'title', widget: string },
                        { label: 'Description', name: 'description', widget: markdown },
                        { label: Image, name: image, widget: image },
                        {
                          label: Links,
                          name: links,
                          widget: list,
                          max: 5,
                          add_to_top: true,
                          fields: [{ label: 'Text', name: 'text', widget: 'string' }, { label: 'URL', name: 'url', widget: 'string' }],
                        },
                      ],
                  },
                ],
            }
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'settings'
    label: 'Settings'
    editor:
      preview: false
    files:
      - file: 'src/pages/settings/index.md'
        label: 'Settings'
        name: 'settings'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'settings' }
          - {
              label: 'Social',
              name: 'social',
              widget: 'object',
              collapsed: false,
              fields:
                [
                  { label: 'StackOverflow', name: 'stackoverflow', widget: 'string', required: false },
                  { label: 'GitHub', name: 'github', widget: 'string', required: false },
                  { label: 'LinkedIn', name: 'linkedin', widget: 'string', required: false },
                  { label: 'Twitter', name: 'twitter', widget: 'string', required: false },
                  { label: 'Instagram', name: 'instagram', widget: 'string', required: false },
                ],
            }
